# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 3 - Test Page Build and Deploy

on:
   workflow_dispatch: 
   workflow_call:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build D:\a\bp\bp\BPCalculator\BPCalculator.csproj --configuration Release
      
      - name: dotnet publish
        run: dotnet publish ./BPCalculator/BPCalculator.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-test
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-test
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_059BE7A1087A4B8DBAD903CAEC617130 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CCA1FE6F9F7434684ACCF6F4DC0A451 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4206752A52D4A7A952EFFBBB528D357 }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BPCalculatortest'
          slot-name: 'Production'
          package: .

          

