# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 3 - Test Page Deploy

on:
   workflow_dispatch: 
   workflow_call:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 

    steps:

      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./published-app

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_049FC73F2C8F4E1BB21B3A9960215648 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87CDE418844448F194769B785A5D7D81 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_87724BE0A8644634BE47F3101E9144CE }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BPCalculatortest'
          slot-name: 'Production'
          package: './published-app'

          

