# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 4 - Test Page Build and Deploy

on:
   workflow_dispatch: 
   workflow_call:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build D:\a\bp\bp\BPCalculator\BPCalculator.csproj --configuration Release
              
      - name: Run Unit Test
        run: dotnet test ./Test/UnitTest/UnitTest.csproj --verbosity normal

      - name: Run PS Test
        run: dotnet test ./Test/PSTest/PSTest.csproj --verbosity normal
          
      - name: Run Page Test
        run: dotnet test ./Test/PageTest/PageTest.csproj --verbosity normal

      - name: Run BDD Test
        run: dotnet test ./Test/BDDTest/BDDTest.csproj --no-build --verbosity normal
      
      - name: dotnet publish
        run: dotnet publish ./BPCalculator/BPCalculator.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-test
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-test
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_059BE7A1087A4B8DBAD903CAEC617130 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CCA1FE6F9F7434684ACCF6F4DC0A451 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4206752A52D4A7A952EFFBBB528D357 }}

      - name: Clean Azure Web App temp directories via Kudu API
        run: |
          $AZURE_ACCESS_TOKEN = az account get-access-token --resource https://management.azure.com --query accessToken -o tsv
          curl "https://bpcalculatortest-crdjejebh3dyazgq.francecentral-01.azurewebsites.net/api/command" `
               -Method POST `
               -Headers @{Authorization="Bearer $AZURE_ACCESS_TOKEN"; "Content-Type"="application/json"} `
               -Body '{"command":"cmd /c rmdir /s /q D:\\local\\Temp\\zipdeploy && mkdir D:\\local\\Temp\\zipdeploy"}'
          curl "https://bpcalculatortest-crdjejebh3dyazgq.francecentral-01.azurewebsites.net/api/command" `
               -Method POST `
               -Headers @{Authorization="Bearer $AZURE_ACCESS_TOKEN"; "Content-Type"="application/json"} `
               -Body '{"command":"cmd /c rmdir /s /q D:\\home\\data && mkdir D:\\home\\data"}'
        shell: pwsh
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BPCalculatortest'
          slot-name: 'Production'
          package: .

          

