name: 4 - Penetration test

env:
  URI: https://bpcalculatortest-crdjejebh3dyazgq.francecentral-01.azurewebsites.net/          
  
on:
   workflow_dispatch: 
   workflow_call:            

jobs:

  zap_baseline_scan:

    runs-on: ubuntu-latest

    steps:

    - name: Pull Docker image for ZAP
      run: docker pull zaproxy/zap-weekly

    - name: Run baseline scan
      run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t ${{env.URI}} -I -r zapreport.html
  
    - uses: actions/upload-artifact@v4
      name: upload ZAP report
      with:
        name: ZAPreport
        path: /report/zapreport.html
