# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 6 - Product Deploy

on:
   workflow_dispatch: 
   workflow_call:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 

    steps:

      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./published-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A65D88E410A44F79457DB5F269899DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEFF4C306DEC4F66AB297AF5902FC3A9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7E5D051325CB496E9B716705C68E6F96 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BPCalculator'
          slot-name: 'Production'
          package: './published-app'

          













