# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Install Coverlet Collector
      run: |
        dotnet add ./Test/UnitTest/UnitTest.csproj package coverlet.collector
        dotnet add ./Test/PSTest/PSTest.csproj package coverlet.collector
        dotnet add ./Test/PageTest/PageTest.csproj package coverlet.collector
        dotnet add ./Test/BDDTest/BDDTest.csproj package coverlet.collector
    
    - name: Clean old test results
      run: rm -rf TestResults || true

    - name: Run Unit Test
      run: dotnet test ./Test/UnitTest/UnitTest.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults --no-build --verbosity 

    - name: Run PS Test
      run: dotnet test ./Test/PSTest/PSTest.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults  --no-build --verbosity normal

    - name: Run Page Test
      run: dotnet test ./Test/PageTest/PageTest.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults --no-build --verbosity normal

    - name: Run BDD Test
      run: dotnet test ./Test/BDDTest/BDDTest.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults --no-build --verbosity normal

    - name: Debug TestResults folder
      run: |
        echo "Current directory:"
        pwd
        echo "List top-level files:"
        ls -l
        echo "List TestResults folder recursively:"
        ls -lR TestResults
    
    - name: Upload raw coverage results
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: TestResults/**/*

